import { test, expect } from '@playwright/test'
import { signIn } from './helpers/auth'

/**
 * e2e: Cross-feature integration — offline checklist + LP audit + R&M
 * WIT-15 Phase 3 Week 4 acceptance test.
 *
 * Validates that all three Phase 3 features coexist and the dashboard
 * correctly reflects data from each module.
 */
test.describe('Cross-feature: offline checklist + LP audit + R&M', () => {
  test.beforeEach(async ({ page }) => {
    await signIn(page)
  })

  test('dashboard shows LP and R&M summary alongside checklist progress', async ({ page }) => {
    await page.goto('/dashboard')

    // Checklist section
    await expect(page.getByText(/checklist/i).first()).toBeVisible()

    // LP Audit section
    await expect(page.getByText(/loss prevention|lp audit/i)).toBeVisible()

    // R&M section
    await expect(page.getByText(/repair.*maintenance|r&m/i)).toBeVisible()
  })

  test('offline checklist completion does not break LP audit navigation', async ({
    page,
    context,
  }) => {
    // Prime checklist SW cache
    await page.goto('/checklist')
    await expect(page.getByRole('heading', { name: /checklist/i })).toBeVisible()

    // Go offline
    await context.setOffline(true)

    // Reload checklist from cache
    await page.reload()
    await expect(page.getByRole('heading', { name: /checklist/i })).toBeVisible()
    await expect(page.getByText(/offline/i)).toBeVisible()

    // Reconnect before navigating to LP audit (requires network)
    await context.setOffline(false)

    // Navigate to LP Audit via bottom nav
    await page.getByRole('link', { name: /lp audit/i }).click()
    await expect(page.url()).toMatch(/\/audit/)
    await expect(page.getByRole('heading', { name: /audit/i })).toBeVisible()
  })

  test('offline checklist completion does not break R&M navigation', async ({
    page,
    context,
  }) => {
    // Prime SW cache
    await page.goto('/checklist')
    await expect(page.getByRole('heading', { name: /checklist/i })).toBeVisible()

    await context.setOffline(true)
    await page.reload()
    await expect(page.getByText(/offline/i)).toBeVisible()

    await context.setOffline(false)

    // Navigate to R&M via bottom nav
    await page.getByRole('link', { name: /r&m/i }).click()
    await expect(page.url()).toMatch(/\/maintenance/)
    await expect(page.getByRole('heading', { name: /maintenance|tickets|r&m/i })).toBeVisible()
  })

  test('LP audit exception appears in dashboard alert', async ({ page }) => {
    // Create an audit run that produces an exception (if audits exist)
    await page.goto('/audit-forms')
    const forms = page.locator('[data-testid="audit-form-card"], .audit-form-item')
    const formCount = await forms.count()

    if (formCount === 0) {
      // No forms — verify empty state is shown
      await expect(page.getByText(/no audit forms|create your first/i)).toBeVisible()
      return
    }

    // Navigate back to dashboard and verify LP section renders
    await page.goto('/dashboard')
    await expect(page.getByText(/loss prevention|lp audit/i)).toBeVisible()
  })

  test('R&M submit flow integrates with manager queue', async ({ page }) => {
    // Submit a cross-feature test ticket
    await page.goto('/maintenance/submit')
    await page.getByLabel(/title/i).fill('Cross-feature E2E test ticket')
    await page.getByLabel(/description/i).fill('Auto-generated by cross-feature e2e test')
    await page.getByLabel(/urgency/i).selectOption('routine')

    await page.getByRole('button', { name: /submit/i }).click()
    await expect(page.getByText(/submitted|ticket created/i)).toBeVisible()

    // Verify it appears in manager queue
    await page.goto('/maintenance')
    await expect(page.getByText('Cross-feature E2E test ticket')).toBeVisible()

    // Verify dashboard R&M section updates (open count > 0)
    await page.goto('/dashboard')
    await expect(page.getByText(/repair.*maintenance|r&m/i)).toBeVisible()
  })

  test('bottom nav is accessible on all Phase 3 pages', async ({ page }) => {
    const routes = ['/checklist', '/audit-forms', '/maintenance', '/dashboard']

    for (const route of routes) {
      await page.goto(route)
      const nav = page.getByRole('navigation', { name: /main navigation/i })
      await expect(nav).toBeVisible()

      // Verify all four nav items are present
      await expect(nav.getByRole('link', { name: /dashboard/i })).toBeVisible()
      await expect(nav.getByRole('link', { name: /checklist/i })).toBeVisible()
      await expect(nav.getByRole('link', { name: /lp audit/i })).toBeVisible()
      await expect(nav.getByRole('link', { name: /r&m/i })).toBeVisible()
    }
  })
})
